# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed012053a1fbf232d7aae1f021fd0536db8e6bd93096b77c371942915508be03fc3f66d1bca35fae317d4384c8cb65a53808758cb3604d3fc01a3b2a2a6eba59

test:
  secret_key_base: b81049fa1a51e9c5d2185b2c97eadc943109797c1049b2720c69cd7cd519b02274eaad7ae868c1261603f56cec8e01917dac68a32d8a20fbb59ac761b4f2525d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
